default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: Test_Project_development

test:
  <<: *default
  database: Test_Project_test

production:
  <<: *default
  database: Test_Project_Production
  username: template_username
  password: <%= ENV['DATABASE_PASSWORD'] %>
