name: Deploy develop branch to Staging site

# Uncomment the following to enable this workflow
# on:
#   push:
#     branches:
#       - develop

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Deploy the application
        uses: dokku/github-action@master
        with:
          ssh_private_key: ${{ secrets.WORKFLOW_PRI_KEY }}
          git_remote_url: 'ssh://dokku@dokku.explorator.ca:22/template'
          branch: develop

